package net.ziling.crm.dao;

import net.ziling.crm.entity.Domain;

public interface DomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_domain
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String domainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_domain
     *
     * @mbggenerated
     */
    int insert(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_domain
     *
     * @mbggenerated
     */
    int insertSelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_domain
     *
     * @mbggenerated
     */
    Domain selectByPrimaryKey(String domainId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Domain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Domain record);
}