package net.ziling.crm.dao;

import net.ziling.crm.entity.RoleDomain;

public interface RoleDomainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String rdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    int insert(RoleDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    int insertSelective(RoleDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    RoleDomain selectByPrimaryKey(String rdId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RoleDomain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RoleDomain record);
}