package net.ziling.crm.dao;

import net.ziling.crm.entity.UserCreditHist;

public interface UserCreditHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_hist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_hist
     *
     * @mbggenerated
     */
    int insert(UserCreditHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_hist
     *
     * @mbggenerated
     */
    int insertSelective(UserCreditHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_hist
     *
     * @mbggenerated
     */
    UserCreditHist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_hist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserCreditHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_credit_hist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserCreditHist record);
}