package net.ziling.crm.dao;

import net.ziling.crm.entity.UserCapacityHist;

public interface UserCapacityHistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    int insert(UserCapacityHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    int insertSelective(UserCapacityHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    UserCapacityHist selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserCapacityHist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserCapacityHist record);
}