package net.ziling.crm.dao;

import net.ziling.crm.entity.UserProject;
import net.ziling.crm.entity.UserProjectKey;

/**
 * Description:
 *
 * UserProjectMapper 数据表映射类
 *
 * @author huaxin
 * @create 2018/01/08 19:54
 */
public interface UserProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserProjectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    int insert(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    int insertSelective(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    UserProject selectByPrimaryKey(UserProjectKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserProject record);
}