package net.ziling.crm.dao;

import net.ziling.crm.entity.UserDuty;
import net.ziling.crm.entity.UserDutyKey;

import java.util.List;

public interface UserDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(UserDutyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    int insert(UserDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    int insertSelective(UserDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    UserDuty selectByPrimaryKey(UserDutyKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UserDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UserDuty record);

    /**
     * 通过userId查找dutyId
     * @param userId
     * @return
     */
    List<String> selectByUserId(String userId);
}