package net.ziling.crm.entity;

/**
 * Description:
 *
 * Duty 实体类
 *
 * @author huaxin
 * @create 2018/01/12 10:36
 */
public class Duty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.duty_id
     *
     * @mbggenerated
     */
    private String dutyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.skill
     *
     * @mbggenerated
     */
    private String skill;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.work_years
     *
     * @mbggenerated
     */
    private String workYears;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.post
     *
     * @mbggenerated
     */
    private String post;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.company
     *
     * @mbggenerated
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.capacity_rate
     *
     * @mbggenerated
     */
    private String capacityRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.credit_rate
     *
     * @mbggenerated
     */
    private String creditRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.rehire_rate
     *
     * @mbggenerated
     */
    private String rehireRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.check_rate
     *
     * @mbggenerated
     */
    private String checkRate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.check_num
     *
     * @mbggenerated
     */
    private Integer checkNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.proceed_num
     *
     * @mbggenerated
     */
    private Integer proceedNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.user_income
     *
     * @mbggenerated
     */
    private Float userIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_duty.month_income
     *
     * @mbggenerated
     */
    private Float monthIncome;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_duty
     *
     * @mbggenerated
     */
    public Duty(String dutyId, String skill, String workYears, String post, String company,
                String capacityRate, String creditRate, String rehireRate, String checkRate,
                Integer checkNum, Integer proceedNum, Float userIncome, Float monthIncome) {
        this.dutyId = dutyId;
        this.skill = skill;
        this.workYears = workYears;
        this.post = post;
        this.company = company;
        this.capacityRate = capacityRate;
        this.creditRate = creditRate;
        this.rehireRate = rehireRate;
        this.checkRate = checkRate;
        this.checkNum = checkNum;
        this.proceedNum = proceedNum;
        this.userIncome = userIncome;
        this.monthIncome = monthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_duty
     *
     * @mbggenerated
     */
    public Duty() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.duty_id
     *
     * @return the value of zc_duty.duty_id
     *
     * @mbggenerated
     */
    public String getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.duty_id
     *
     * @param dutyId the value for zc_duty.duty_id
     *
     * @mbggenerated
     */
    public void setDutyId(String dutyId) {
        this.dutyId = dutyId == null ? null : dutyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.skill
     *
     * @return the value of zc_duty.skill
     *
     * @mbggenerated
     */
    public String getSkill() {
        return skill;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.skill
     *
     * @param skill the value for zc_duty.skill
     *
     * @mbggenerated
     */
    public void setSkill(String skill) {
        this.skill = skill == null ? null : skill.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.work_years
     *
     * @return the value of zc_duty.work_years
     *
     * @mbggenerated
     */
    public String getWorkYears() {
        return workYears;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.work_years
     *
     * @param workYears the value for zc_duty.work_years
     *
     * @mbggenerated
     */
    public void setWorkYears(String workYears) {
        this.workYears = workYears == null ? null : workYears.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.post
     *
     * @return the value of zc_duty.post
     *
     * @mbggenerated
     */
    public String getPost() {
        return post;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.post
     *
     * @param post the value for zc_duty.post
     *
     * @mbggenerated
     */
    public void setPost(String post) {
        this.post = post == null ? null : post.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.company
     *
     * @return the value of zc_duty.company
     *
     * @mbggenerated
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.company
     *
     * @param company the value for zc_duty.company
     *
     * @mbggenerated
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.capacity_rate
     *
     * @return the value of zc_duty.capacity_rate
     *
     * @mbggenerated
     */
    public String getCapacityRate() {
        return capacityRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.capacity_rate
     *
     * @param capacityRate the value for zc_duty.capacity_rate
     *
     * @mbggenerated
     */
    public void setCapacityRate(String capacityRate) {
        this.capacityRate = capacityRate == null ? null : capacityRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.credit_rate
     *
     * @return the value of zc_duty.credit_rate
     *
     * @mbggenerated
     */
    public String getCreditRate() {
        return creditRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.credit_rate
     *
     * @param creditRate the value for zc_duty.credit_rate
     *
     * @mbggenerated
     */
    public void setCreditRate(String creditRate) {
        this.creditRate = creditRate == null ? null : creditRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.rehire_rate
     *
     * @return the value of zc_duty.rehire_rate
     *
     * @mbggenerated
     */
    public String getRehireRate() {
        return rehireRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.rehire_rate
     *
     * @param rehireRate the value for zc_duty.rehire_rate
     *
     * @mbggenerated
     */
    public void setRehireRate(String rehireRate) {
        this.rehireRate = rehireRate == null ? null : rehireRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.check_rate
     *
     * @return the value of zc_duty.check_rate
     *
     * @mbggenerated
     */
    public String getCheckRate() {
        return checkRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.check_rate
     *
     * @param checkRate the value for zc_duty.check_rate
     *
     * @mbggenerated
     */
    public void setCheckRate(String checkRate) {
        this.checkRate = checkRate == null ? null : checkRate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.check_num
     *
     * @return the value of zc_duty.check_num
     *
     * @mbggenerated
     */
    public Integer getCheckNum() {
        return checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.check_num
     *
     * @param checkNum the value for zc_duty.check_num
     *
     * @mbggenerated
     */
    public void setCheckNum(Integer checkNum) {
        this.checkNum = checkNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.proceed_num
     *
     * @return the value of zc_duty.proceed_num
     *
     * @mbggenerated
     */
    public Integer getProceedNum() {
        return proceedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.proceed_num
     *
     * @param proceedNum the value for zc_duty.proceed_num
     *
     * @mbggenerated
     */
    public void setProceedNum(Integer proceedNum) {
        this.proceedNum = proceedNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.user_income
     *
     * @return the value of zc_duty.user_income
     *
     * @mbggenerated
     */
    public Float getUserIncome() {
        return userIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.user_income
     *
     * @param userIncome the value for zc_duty.user_income
     *
     * @mbggenerated
     */
    public void setUserIncome(Float userIncome) {
        this.userIncome = userIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_duty.month_income
     *
     * @return the value of zc_duty.month_income
     *
     * @mbggenerated
     */
    public Float getMonthIncome() {
        return monthIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_duty.month_income
     *
     * @param monthIncome the value for zc_duty.month_income
     *
     * @mbggenerated
     */
    public void setMonthIncome(Float monthIncome) {
        this.monthIncome = monthIncome;
    }

    /**
     * 检查是否可以更新
     * @author wzy
     * @return bool
     */
    public boolean isUpdatable(){
        return !( this.skill == null && this.workYears == null &&
        this.post == null && this.company == null &&
        this.capacityRate == null &&  this.creditRate == null &&
        this.rehireRate == null && this.checkRate == null &&
        this.checkNum == null && this.proceedNum == null &&
        this.userIncome == null && this.monthIncome == null);
    }
}