package net.ziling.crm.entity;

/**
 * Description:
 *
 * Project 实体类
 *
 * @author huaxin
 * @create 2018/01/12 10:36
 */
public class Project {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_project.pro_id
     *
     * @mbggenerated
     */
    private String proId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_project.project_name
     *
     * @mbggenerated
     */
    private String projectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_project.project_type
     *
     * @mbggenerated
     */
    private String projectType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_project.project_price
     *
     * @mbggenerated
     */
    private String projectPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_project.project_income
     *
     * @mbggenerated
     */
    private String projectIncome;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_project.project_state
     *
     * @mbggenerated
     */
    private String projectState;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_project
     *
     * @mbggenerated
     */
    public Project(String proId, String projectName, String projectType, String projectPrice, String projectIncome, String projectState) {
        this.proId = proId;
        this.projectName = projectName;
        this.projectType = projectType;
        this.projectPrice = projectPrice;
        this.projectIncome = projectIncome;
        this.projectState = projectState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_project
     *
     * @mbggenerated
     */
    public Project() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_project.pro_id
     *
     * @return the value of zc_project.pro_id
     *
     * @mbggenerated
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_project.pro_id
     *
     * @param proId the value for zc_project.pro_id
     *
     * @mbggenerated
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_project.project_name
     *
     * @return the value of zc_project.project_name
     *
     * @mbggenerated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_project.project_name
     *
     * @param projectName the value for zc_project.project_name
     *
     * @mbggenerated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_project.project_type
     *
     * @return the value of zc_project.project_type
     *
     * @mbggenerated
     */
    public String getProjectType() {
        return projectType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_project.project_type
     *
     * @param projectType the value for zc_project.project_type
     *
     * @mbggenerated
     */
    public void setProjectType(String projectType) {
        this.projectType = projectType == null ? null : projectType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_project.project_price
     *
     * @return the value of zc_project.project_price
     *
     * @mbggenerated
     */
    public String getProjectPrice() {
        return projectPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_project.project_price
     *
     * @param projectPrice the value for zc_project.project_price
     *
     * @mbggenerated
     */
    public void setProjectPrice(String projectPrice) {
        this.projectPrice = projectPrice == null ? null : projectPrice.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_project.project_income
     *
     * @return the value of zc_project.project_income
     *
     * @mbggenerated
     */
    public String getProjectIncome() {
        return projectIncome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_project.project_income
     *
     * @param projectIncome the value for zc_project.project_income
     *
     * @mbggenerated
     */
    public void setProjectIncome(String projectIncome) {
        this.projectIncome = projectIncome == null ? null : projectIncome.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_project.project_state
     *
     * @return the value of zc_project.project_state
     *
     * @mbggenerated
     */
    public String getProjectState() {
        return projectState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_project.project_state
     *
     * @param projectState the value for zc_project.project_state
     *
     * @mbggenerated
     */
    public void setProjectState(String projectState) {
        this.projectState = projectState == null ? null : projectState.trim();
    }
}