package net.ziling.crm.entity;

/**
 * Description:
 *
 * RoleDomain 实体类
 *
 * @author huaxin
 * @create 2018/01/08 19:54
 */
public class RoleDomain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_role_domain.rd_id
     *
     * @mbggenerated
     */
    private String rdId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_role_domain.role_id
     *
     * @mbggenerated
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column zc_role_domain.domain_id
     *
     * @mbggenerated
     */
    private String domainId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    public RoleDomain(String rdId, String roleId, String domainId) {
        this.rdId = rdId;
        this.roleId = roleId;
        this.domainId = domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table zc_role_domain
     *
     * @mbggenerated
     */
    public RoleDomain() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_role_domain.rd_id
     *
     * @return the value of zc_role_domain.rd_id
     *
     * @mbggenerated
     */
    public String getRdId() {
        return rdId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_role_domain.rd_id
     *
     * @param rdId the value for zc_role_domain.rd_id
     *
     * @mbggenerated
     */
    public void setRdId(String rdId) {
        this.rdId = rdId == null ? null : rdId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_role_domain.role_id
     *
     * @return the value of zc_role_domain.role_id
     *
     * @mbggenerated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_role_domain.role_id
     *
     * @param roleId the value for zc_role_domain.role_id
     *
     * @mbggenerated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column zc_role_domain.domain_id
     *
     * @return the value of zc_role_domain.domain_id
     *
     * @mbggenerated
     */
    public String getDomainId() {
        return domainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column zc_role_domain.domain_id
     *
     * @param domainId the value for zc_role_domain.domain_id
     *
     * @mbggenerated
     */
    public void setDomainId(String domainId) {
        this.domainId = domainId == null ? null : domainId.trim();
    }
}