package net.ziling.crm.entity;

public class UserCapacityHist {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_capacity_hist.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_capacity_hist.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_capacity_hist.capacity_rate
     *
     * @mbggenerated
     */
    private String capacityRate;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    public UserCapacityHist(Integer id, String userId, String capacityRate) {
        this.id = id;
        this.userId = userId;
        this.capacityRate = capacityRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_capacity_hist
     *
     * @mbggenerated
     */
    public UserCapacityHist() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_capacity_hist.id
     *
     * @return the value of user_capacity_hist.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_capacity_hist.id
     *
     * @param id the value for user_capacity_hist.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_capacity_hist.user_id
     *
     * @return the value of user_capacity_hist.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_capacity_hist.user_id
     *
     * @param userId the value for user_capacity_hist.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_capacity_hist.capacity_rate
     *
     * @return the value of user_capacity_hist.capacity_rate
     *
     * @mbggenerated
     */
    public String getCapacityRate() {
        return capacityRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_capacity_hist.capacity_rate
     *
     * @param capacityRate the value for user_capacity_hist.capacity_rate
     *
     * @mbggenerated
     */
    public void setCapacityRate(String capacityRate) {
        this.capacityRate = capacityRate == null ? null : capacityRate.trim();
    }
}