package net.ziling.crm.entity;

/**
 * Description:
 *
 * UserDuty 实体类
 *
 * @author huaxin
 * @create 2018/01/12 10:36
 */
public class UserDuty extends UserDutyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_duty.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    public UserDuty(String userId, String dutyId, String desc) {
        super(userId, dutyId);
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    public UserDuty() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_duty.desc
     *
     * @return the value of user_duty.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_duty.desc
     *
     * @param desc the value for user_duty.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}