package net.ziling.crm.entity;

/**
 * Description:
 *
 * UserProject 实体类
 *
 * @author huaxin
 * @create 2018/01/12 10:36
 */
public class UserProject extends UserProjectKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pro.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    public UserProject(String userId, String proId, String desc) {
        super(userId, proId);
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    public UserProject() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pro.desc
     *
     * @return the value of user_pro.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pro.desc
     *
     * @param desc the value for user_pro.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }
}