package net.ziling.crm.entity;

/**
 * Description:
 *
 * UserDutyKey 实体类
 *
 * @author huaxin
 * @create 2018/01/12 10:36
 */
public class UserDutyKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_duty.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_duty.duty_id
     *
     * @mbggenerated
     */
    private String dutyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    public UserDutyKey(String userId, String dutyId) {
        this.userId = userId;
        this.dutyId = dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_duty
     *
     * @mbggenerated
     */
    public UserDutyKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_duty.user_id
     *
     * @return the value of user_duty.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_duty.user_id
     *
     * @param userId the value for user_duty.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_duty.duty_id
     *
     * @return the value of user_duty.duty_id
     *
     * @mbggenerated
     */
    public String getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_duty.duty_id
     *
     * @param dutyId the value for user_duty.duty_id
     *
     * @mbggenerated
     */
    public void setDutyId(String dutyId) {
        this.dutyId = dutyId == null ? null : dutyId.trim();
    }
}