package net.ziling.crm.entity;

/**
 * Description:
 *
 * UserProjectKey 实体类
 *
 * @author huaxin
 * @create 2018/01/12 10:36
 */
public class UserProjectKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pro.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_pro.pro_id
     *
     * @mbggenerated
     */
    private String proId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    public UserProjectKey(String userId, String proId) {
        this.userId = userId;
        this.proId = proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_pro
     *
     * @mbggenerated
     */
    public UserProjectKey() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pro.user_id
     *
     * @return the value of user_pro.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pro.user_id
     *
     * @param userId the value for user_pro.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_pro.pro_id
     *
     * @return the value of user_pro.pro_id
     *
     * @mbggenerated
     */
    public String getProId() {
        return proId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_pro.pro_id
     *
     * @param proId the value for user_pro.pro_id
     *
     * @mbggenerated
     */
    public void setProId(String proId) {
        this.proId = proId == null ? null : proId.trim();
    }
}